export const navigationLinks = [
  { href: '/demo/shadcn-atoms/card', text: 'Card' },
  { href: '/demo/shadcn-atoms/button', text: 'Button' },
  { href: '/demo/shadcn-atoms/accordian', text: 'Accordian' },
  { href: '/demo/shadcn-atoms/toast', text: 'Toast' },
  { href: '/demo/shadcn-atoms/table', text: 'Table' },
  { href: '/demo/shadcn-atoms/checkbox', text: 'Checkbox' },
  { href: '/demo/shadcn-atoms/alert', text: 'Alert' },
  { href: '/demo/shadcn-atoms/alertDialog', text: 'Alert Dialog' },
  { href: '/demo/shadcn-atoms/avatar', text: 'Avatar' },
  { href: '/demo/shadcn-atoms/badge', text: 'Badge' },
  { href: '/demo/shadcn-atoms/collapsible', text: 'Collapsible' },
  { href: '/demo/shadcn-atoms/command', text: 'Command' },
  { href: '/demo/shadcn-atoms/dialog', text: 'Dialog' },
  { href: '/demo/shadcn-atoms/drawer', text: 'Drawer' },
  { href: '/demo/shadcn-atoms/hover-card', text: 'Hover  Card' },
  { href: '/demo/shadcn-atoms/input', text: 'Input' },
  { href: '/demo/shadcn-atoms/label', text: 'Label' },
  { href: '/demo/shadcn-atoms/menubar', text: 'Menubar' },
  { href: '/demo/shadcn-atoms/navigation-menu', text: 'Navigation Menu' },
  { href: '/demo/shadcn-atoms/pagination', text: 'Pagination' },
  { href: '/demo/shadcn-atoms/popover', text: 'Popover' },
  { href: '/demo/shadcn-atoms/progress', text: 'Progress' },
  { href: '/demo/shadcn-atoms/radio-group', text: 'Radio Group' },
  { href: '/demo/shadcn-atoms/select', text: 'Select' },
  { href: '/demo/shadcn-atoms/skeleton', text: 'Skeleton' },
  { href: '/demo/shadcn-atoms/switch', text: 'Switch' },
  { href: '/demo/shadcn-atoms/tabs', text: 'Tabs' },
  { href: '/demo/shadcn-atoms/textarea', text: 'Textarea' },
  { href: '/demo/shadcn-atoms/toggle', text: 'Toggle' },
  { href: '/demo/shadcn-atoms/tooltip', text: 'Tooltip' },
];
